services:
  postgres:
    image: postgres:16
    container_name: bazaar-postgres
    restart: always
    environment:
      POSTGRES_DB: bazaar_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2107072
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: