spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cloudinary credentials from environment variables.
# Example PowerShell:
# $env:CLOUDINARY_CLOUD_NAME="your_cloud_name"
# $env:CLOUDINARY_API_KEY="your_api_key"
# $env:CLOUDINARY_API_SECRET="your_api_secret"
cloudinary.cloud-name=dgwdywso3
cloudinary.api-key=379879192534242
cloudinary.api-secret=d4Vy113OZ7YKZpsLuRbXHXaL_pc

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB